<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Optimize>false</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Tests/**/*.cs" />
    <Compile Remove="Core/**/*.cs" />
    <Compile Remove="Web/**/*.cs" />
    <Compile Remove="Importer/**/*.cs" />
    <Compile Remove="Backups/**/*.cs" />
    <Compile Remove="MarketProxy/**/*.cs" />
  </ItemGroup>
</Project>
